### ISSUE TITLE
using utility from makedepend before checking it

### ISSUE THREAD

**Issue by Ashark** [codibit/davinci-resolve-studio#1]
In your pkgbuild you use`xdg-user-dir DOWNLOAD`, like in davinci-resolve pkgbuild v15.2.2-1. It is run outside any function before source array. The problem is that makedepends array is checked after source check, but you want to use this makedepend before source check (because you want to link it to download directory).
In this case I just removed archive from source array and then use it manually in prepare() function.
You can see my solution of this [here](https://gist.github.com/Ashark/a194db36c8acd53f3cff496b617628fb/e2c5f24c01c19b2473a382b8e98ab2d9b7df56cd).

**Comment by victor-vanherpt** [comment]
Hi! Thanks, I will look into it

**Comment by victor-vanherpt** [comment]
I've now implemented your suggestion, thanks @Ashark  :+1:
