### ISSUE TITLE
Pull fails when file is in Download or current directory

### ISSUE THREAD

**Issue by Yabbo** [codibit/davinci-resolve-studio#3]
    ~/Downloads  yay -S davinci-resolve-studio                                                                                                        ✔ 
:: Checking for conflicts...
:: Checking for inner conflicts...
[Aur:1]  davinci-resolve-studio-17.2-2

  1 davinci-resolve-studio                   (Build Files Exist)
==> Packages to cleanBuild?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==> 
:: PKGBUILD up to date, Skipping (1/1): davinci-resolve-studio
  1 davinci-resolve-studio                   (Build Files Exist)
==> Diffs to show?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==> 
:: (1/1) Parsing SRCINFO: davinci-resolve-studio
==> Making package: davinci-resolve-studio 17.2-2 (Thu 20 May 2021 04:55:12 PM EDT)
==> Retrieving sources...
  -> Downloading DaVinci_Resolve_Studio_17.2_Linux.zip...
curl: (3) URL using bad/illegal format or missing URL
curl: (6) Could not resolve host: ''
Warning: Problem : timeout. Will retry in 3 seconds. 3 retries left.
curl: (6) Could not resolve host: ''
Warning: Problem : timeout. Will retry in 3 seconds. 2 retries left.
^C
==> ERROR: Aborted by user! Exiting...

file is downloaded and sitting in the Downloads Directory. 

    ~/Downloads  ls                                                                                                                       INT ✘  9s   
 DaVinci_Resolve_Studio_17.2_Linux.run   DaVinci_Resolve_Studio_17.2_Linux.zip   Linux_Installation_Instructions.pdf   NVIDIA-Linux-x86_64-460.80.run

for some reason its still trying to pull the file

**Comment by victor-vanherpt** [comment]
Hello @Yabbo, unfortunately this repository is outdated and no longer mantained.
Please check the one available at https://aur.archlinux.org/packages/davinci-resolve-studio
and find more information at https://wiki.archlinux.org/title/DaVinci_Resolve
